### ISSUE TITLE
a couple of tracks made with *only* geonkick 

### ISSUE THREAD

**Issue by rghvdberg** [iurie-sw/geonkick#106]
I thought you'd like to know about this :-)

Libre Music Challenge #2 - Make a Jingle With Geonkick

The Libre Music Challenge is an event that originated in the chat server run by producer/musician/youtuber Unfa.
Every 1st Sunday of the month a new challenge starts, and we try to make if fun and educational.
We use only free audio software.
This month one was asked to make a short jingle using only Geonkick as the instruments.

https://archive.org/details/libre-music-challenge-2

The music is licensed CC BY-SA 4.0, so you can use them if you feel like it.

**Comment by iurienistor** [comment]
What is this? :)

**Comment by rghvdberg** [comment]
I pressed [enter] too soon :-) 
original message updated

**Comment by iurienistor** [comment]
Wow! That's really cool. I like them!

**Comment by rghvdberg** [comment]
you can close this issue now if you like, I didn't know another way to contact you ;-)

**Comment by iurienistor** [comment]
Thank you :)
