### ISSUE TITLE
Drag and drop samples to oscillators, better sample file dialog

### ISSUE THREAD

**Issue by Tremeschin** [iurie-sw/geonkick#107]
For some reason never thought Geonkick could be used as a sampler but only as a drum synth plugin, tho I had two workflow issues while trying to do so that killed this idea.

- Can't drag and drop samples from a file manager to a oscillator or file dialog GUI
- Sample file dialog isn't really the best, no previews and file manager shortcuts

I think either a drag and drop of sample to a oscillator or a better file dialog would open a lot of possibilities with Geonkick.

As it stores the sample on the metadata rather than linking to the files like samplv1 does ( making it impossible to share a DAW project file and loading with different directories AFAIK ), I personally would use Geonkick as both a synth and a sampler from now on if those features are implemented.

**Comment by Tremeschin** [comment]
Enhancement, feature tags

**Comment by apoorv569** [comment]
I would like to see drag and drop support also.

**Comment by iurienistor** [comment]
Yes, I absolutely agree, now is quite hard to work with the file dialog. I'll try to implement drag and drop in the next release and make it easyer to select files, samples.

**Comment by iurienistor** [comment]
I am not sure i understood what you mean with "feature labels". Please, can you explain?

**Comment by Tremeschin** [comment]
@iurienistor Ah I was just marking the labels this issue should got from you as I don't have permission to do so :)

**Comment by iurienistor** [comment]
I think I have already implemented the drag and drop. The problem is that this feature in order to work there is a need also the hosts to support this feature. Currently I think no host on GNU/Linux supports this until the next release of the library libsuil will  be released and which is used by all LV2 hosts. I have tested with Ardour built with this latest implementation of libsuil and drag  and drop works. There might be Ardour to support drag and drop in the ofical builds if it is built specifically with this latest libsuil.

Thus, I am implementing the second option - samples browser.

**Comment by Tremeschin** [comment]
@iurienistor Ah, it's a wider problem than I thought then..

If you don't mind, I'll suggest a few things that I find annoying and what I'd like to see on a good sample browser

- When selecting a file that is a symlink, don't change the "working directory" of the sample browser itself, happens with samplv1 we get redirected to where that sample is on disk (asking this because I copy the symlink of samples I used on tracks of Ardour sessions)

- If possible use a tree folder style (toggleable with traditional folder view modes?), it's a bit easier to navigate through files when going through multiple directories

- Sound preview is basically a must for me, though I don't mind not having it, just makes things easier and saves a lot of clicks

- Would be nice if the sample browser remembers what folder you were selecting stuff, perhaps save the persistent data under `~/.config/geonkick` or something? (not sure if this already exists, probably yes because the drum kits)

I think those are the main points that would make Geonkick workflow really top notch as a sampler :)

**Comment by iurienistor** [comment]
Thank you for your suggestion, they are important and this helps to improve Geonkick.

>     * If possible use a tree folder style (toggleable with traditional folder view modes?), it's a bit easier to navigate through files when going through multiple directories

It would be really handful, but since I am not using a common GUI toolkit like Qt or GTK (that has tree view and other ready widgets) but a self-developed one [Redkite](https://github.com/iurie-sw/redkite) there is a need such thing to be developed. Probably for now will be easier to develop a history of visits, and when I'll develop for Redkite tree view than to add also this.

>     * Sound preview is basically a must for me, though I don't mind not having it, just makes things easier and saves a lot of clicks

Yes, is necessary. There will be sound preview and probably visual preview. But for now sound preview will be only the first maximum 4 seconds, because Geonkick doesn't support longer sounds than 4 seconds. 

>     * Would be nice if the sample browser remembers what folder you were selecting stuff, perhaps save the persistent data under `~/.config/geonkick` or something? (not sure if this already exists, probably yes because the drum kits)

Yes, this is necessary, and also the history of visits will be stored. Probably there will be added also some default folders like Desktop, Download, etc.

> I think those are the main points that would make Geonkick workflow really top notch as a sampler :)

I wanted to mention that Geonkick even if plays samples, it is desiged only for percussive sounds, it doesn't support polyphony, i.e. not useful for non percussive tings.

**Comment by Tremeschin** [comment]
> I wanted to mention that Geonkick even if plays samples, it is desiged only for percussive sounds, it doesn't support polyphony, i.e. not useful for non percussive tings.

Yes, that is exactly my use case of Geonkick, longer samples I prefer to make them audio regions on Ardour for having a sense of "size" and "space", because percussive sounds don't overlap very often with instruments, as opposed to longer samples / FX that do (like reversed recordings, sweeps, crashes etc)

Oh just another thing I realized, there could be a improvement on editing capability of the samples:

- I can't phase the sample to cut a bit of the start, shift it to the left, "negative start value", perhaps would be good if the phase slider is at the middle and we could advance the starting point, we can only push it backwards

I'm looking forward to the upcoming improvements based on these suggestions, thank you a lot for being open and listening!!

**Comment by iurienistor** [comment]
> I can't phase the sample to cut a bit of the start, shift it to the left, "negative start value", perhaps would be good if the phase slider is at the middle and we could advance the starting point, we can only push it backwards

Ah, ok, I think is good idea.

**Comment by apoorv569** [comment]
Just thinking a option for pitch shifting the sample and ability to stretch the sample would also be a great feature to have. Also if possible it would be great, if one could make longer sounds than 4 seconds, as I was trying a make a sweep and it was not long enough, so I ended up using `Zyn-fusion` for it. Also a playhead marker on the `Geonkick` display would be nice which syncs to host DAW, to be able to show position of the sample, when played. As it for file browser, if it remembers the last folder I was on, and has playback/preview capabilities, when selecting samples, I think it will serve its purpose, doesn't have to be a `nautilus` like file picker or something like that, and with a clean interface also.

Just think out loud here, I think a new section for sample would be nice, like there are 4 sections right now on the main window, Osc1, Osc2, Noise and General, it would be great to make a new section for samples, as quite a few features have been requested here already and maybe more will be requested later, for keeping the UI clean, a separate section for samples and in between the 4 button after the `L3` button there would be a button for sample manipulation, also renaming General to Global would be nice too. And for the effects below like distortion, compression, layer mixer, it would be nice to have a separate section called effect or mixer or something, on the right below Controls, Kit and those buttons, and the `e` button on the distortion settings, on the new section you can create a different UI totally to mix and edit efffects, rather having the same controls for Osc1, Osc2 and all. And a ability to copy and paste layers would also be a great.

OK, I think I have shifted the topic from sample editor features to UI now.

**Comment by iurienistor** [comment]
@apoorv569 Hi! Thank you for suggestions. Yes, please, create another issue on UI suggestions.

#### Samples section 

 A separate section / "oscillator" for samples is quite an interesting idea, thus, I have created the issue https://github.com/iurie-sw/geonkick/issues/114. The only problem is that there will be possible only one sample per layer, currently is possible two samples per layer. But I think I have an idea how to solve this. Also, probably I'll move osc1 and osc2 in the same section with  "tabs" osc1, and osc2. Than I'll have an additional free section for samples.

#### Longer sounds

Yes, thought about this, I'll try to make it longer... The problem with longer sounds it means it requires more processing and this slows down the real-time visualization and audition when someone modifies the parameter (created https://github.com/iurie-sw/geonkick/issues/115). 

#### Playhead marker

I'll try to see if this is possible and if this will not complicated things, especially to slow the real-time visualization (created https://github.com/iurie-sw/geonkick/issues/116).

**Comment by apoorv569** [comment]
Thanks, I made a separate issue for UI Suggestions #117

**Comment by eamonn-tobin** [comment]
Hi, I came here to suggest this exact feature. I don't understand all the technicalities but I'm glad that it is considered. Anyway, thanks for the great work :-)
