### ISSUE TITLE
"Fanout" option creates 32 mono channels rather than 16 stereo

### ISSUE THREAD

**Issue by Ploppz** [iurie-sw/geonkick#109]
Earlier it produced 16 stereo channels for me, but now 32 mono channels.
Pairs of channels like this
 ![31 Sunday-slop7509](https://user-images.githubusercontent.com/4773287/89738449-e1f3bf80-da78-11ea-97fd-c33da1974227.png)

This is obviously cumbersome to work with in case I want to apply any effect plugins on any of the (L+R) channels.

OS: Arch Linux
Geonkick: 2.3.3-1 from official repo

**Comment by iurienistor** [comment]
Hi, thank you. I will check but I suspect this might be from the host.

**Comment by iurienistor** [comment]
@Ploppz I think this was a bug of Ardour, they fixed this issue. - https://tracker.ardour.org/view.php?id=8307

**Comment by iurienistor** [comment]
@Ploppz Hi! Now it should be fixed.

**Comment by Ploppz** [comment]
Great, thanks!
