### ISSUE TITLE
Stereo noise generator option

### ISSUE THREAD

**Issue by iurienistor** [iurie-sw/geonkick#11]
Stereo noise option for noise Generator.

**Comment by iurienistor** [comment]
This one doesn't make sense since a layer is actually mono. In order this to work it owuld mean Geonkick to make it to make two channels of synthesis, but this will not make sens for graph. Thus, I think I'll drop this for now.

**Comment by magnetophon** [comment]
Would it be that bad to just display one side of the graph?

I'd love to have stereo noise!

**Comment by iurienistor** [comment]
@magnetophon Thank you, I'll think how to implemented this in order to make sense. I scheduled this for version 2.0, this will be after the version 1.10 that I am going to release soon.

**Comment by magnetophon** [comment]
Great! Thanks!
