### ISSUE TITLE
Loading a preset, the Kit tab is glitched (among other: only shows one entry)

### ISSUE THREAD

**Issue by Ploppz** [iurie-sw/geonkick#112]
I installed `geonkick-git` from AUR so I am on d5c00b9.
However I also had this problem on the official `geonkick` package.

When I load a preset I made earlier, it works fine. I press MIDI keys A through C and get 4 different percussion sounds I made earlier.
However, in the Kits tab, there is only one entry (the first one, titled "Kick").
![32 Thursday-slop0148](https://user-images.githubusercontent.com/4773287/90183677-30c09280-ddb4-11ea-9793-c6bf7f84c505.png)

When I click `+` to create a new thing, I cannot select it to edit it. Like it's just there, and no other row than `Kick` will be selected ever.
I could send you the preset if you tell me how.

**Edit:** Oh and after a little while, this happens: it goes from one selected `Kick` and several unselected ones, to:
![32 Thursday-slop0597](https://user-images.githubusercontent.com/4773287/90183960-af1d3480-ddb4-11ea-841b-9761f98aec60.png)

Actually this is how I remember it happened on the official `geonkick` package as well a couple of days ago so it is very reproducible on my computer.

**Edit 2:** Oh this is getting more and more interesting: Now when I add more things, I can click them but it will in most cases select two simultaneously:
![32 Thursday-slop0724](https://user-images.githubusercontent.com/4773287/90184191-03c0af80-ddb5-11ea-9497-2d0a0ad218f4.png)
![32 Thursday-slop0729](https://user-images.githubusercontent.com/4773287/90184194-04594600-ddb5-11ea-9ca7-566db0a1b940.png)

**Comment by iurienistor** [comment]
Hi! Thnak you for reporting this. Coud you send me the preset in order to reproduce? You can attach it even here or send it to:  iur.nistor@gmail.com

**Comment by iurienistor** [comment]
I've made an update. Can try now from the master?

**Comment by Ploppz** [comment]
Sorry for the delay. It seems fixed, thanks!
