### ISSUE TITLE
UI Suggestions.

### ISSUE THREAD

**Issue by apoorv569** [iurie-sw/geonkick#117]
Just think out loud here, I think a new section for sample would be nice, like there are 4 sections right now on the main window, Osc1, Osc2, Noise and General, it would be great to make a new section for samples, as quite a few features have been requested here already and maybe more will be requested later, for keeping the UI clean, a separate section for samples and in between the 4 button after the `L3` button there would be a button for sample manipulation, also renaming General to Global would be nice too. And for the effects below like distortion, compression, layer mixer, it would be nice to have a separate section called effect or mixer or something, on the right below Controls, Kit and those buttons, and the `e` button on the distortion settings, on the new section you can create a different UI totally to mix and edit efffects, rather having the same controls for Osc1, Osc2 and all. And a ability to copy and paste layers would also be a great.

**Comment by iurienistor** [comment]
Some things from here were implemented in 
https://github.com/iurie-sw/geonkick/issues/107
https://github.com/iurie-sw/geonkick/issues/114
Thank you!
