### ISSUE TITLE
Binary does not include manpage

### ISSUE THREAD

**Issue by eeickmeyer** [iurie-sw/geonkick#118]
Hi there,

Much like when I packaged redkite for Ubuntu, I'm getting a warning about /usr/bin/geonkick not having a manpage. This should be corrected at your earliest convenience. In the meantime, I'm citing the extensive documentation provided as the manual. However, if you wouldn't mind, please create a manpage at your earliest convenience.

Thanks!

**Comment by iurienistor** [comment]
@eeickmeyer Hi! Thank you. I'll create the manpage as soon as possible :)

**Comment by iurienistor** [comment]
I have added the man page for geonkick executable. In the next releases I'll add some command options to geonkick in order to comply with GNU standard - https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html

**Comment by eeickmeyer** [comment]
Excellent! 2.3.6 is awaiting review, so once it's accepted I'll be able to update to 2.3.7 with the manpage. :)
