### ISSUE TITLE
Make it sample rate agnostic

### ISSUE THREAD

**Issue by Ploppz** [iurie-sw/geonkick#123]
I have to use a sample rate of 96k in JACK due to my motherboard choking on 48k or lower.

So I had the issue in Geonkick that everything I made sounded so high pitched, even if I go down to 100Hz. Could even hear 40Hz with my headphones that support only down to 80Hz. Someone told me that Geonkick expects 48k sample rate, so that in my setup everything will be one octave higher.
Would be great if this could be fixed!

**Comment by iurienistor** [comment]
Hi! Geonkick now supports only 48k. For now I don't know when I'll implement for it to support other sample rate.

**Comment by iurienistor** [comment]
I have scheduled this feature to be implemented in the next release.

**Comment by iurienistor** [comment]
Implemented. The only problem will be with presets with samples. If the preset that contains samples are saved for one sample rate, will be pitch shifted for other sample rates. For purely synthesized presets there is no problem.
