### ISSUE TITLE
Ardour Fan Out not working properly

### ISSUE THREAD

**Issue by unfa** [iurie-sw/geonkick#130]
This is weird:
![image](https://user-images.githubusercontent.com/491704/96731748-e2cd9980-13b7-11eb-9e48-d69a3b427f79.png)

Geonkick 2.3.8, Ardour 6.3.177
Manajro Linux

Can anybody confirm?

**Comment by iurienistor** [comment]
Yes, both Geonkick output channels are directed to the left channel. I know that @x42 made a fix in Geonkick regrading a bug for fan out. For know I am not sure if this second issue comes from Geonkick or the host because the audio ports seems to be defined correctly and the groups too. But I'll investigate more since I am not very good on LV2 ttls manifesto. I have compared with Yoshimi-muti that seems to be fanout correctly but Yoshimi doesn use groups for stereo channels as Geonkick. I ask Ardour developers if they can help with an advice here.

**Comment by iurienistor** [comment]
Ok, if I am removing groups from the manifesto, than fanout are routed done correctly in Ardour.

**Comment by x42** [comment]
Try expanding the stereo-group from

https://github.com/iurie-sw/geonkick/blob/6c69359f0c8a783dc1a4d3e1d0c1547a3ff11742/plugin/lv2/geonkick.lv2/geonkick.ttl#L275-L279

to 
```
ls:Out1 
  a pg:OutputGroup, pg:DiscreteGroup;
     rdfs:label "Out 1" ; 
     lv2:symbol "out1" .                                                                                                                                                      
  pg:element [
    lv2:index 0 ;
    lv2:designation pg:left
  ] , [
    lv2:index 1 ;
    lv2:designation pg:right
  ] .
```

The problem exists if the target system does not have "port-groups.ttl" in LV2_PATH. liblilv can only expand  `pg:StereoGroup` when port-groups.ttl is parsed. On most GNU/Linuxsystems `/usr/lib/lv2/port-groups.lv2/port-groups.ttl` only comes with `lv2-dev`. and it's not usually installed on Windows and Mac Systems

**Comment by iurienistor** [comment]
@x42 Thank you! I'll try make these changes to see how it works. If not than probably I'll just remove the groups.

**Comment by iurienistor** [comment]
@x42 It works now, thank you!

**Comment by drobilla** [comment]
It is generally expected that the LV2 spec bundles installed and available in LV2_PATH.  However,

> liblilv can only expand pg:StereoGroup when port-groups.ttl is parsed

Isn't quite right.  As long as the prefix is defined in the file (which is always required to use a prefix in that file), it will at least parse correctly, though the detailed data in port-groups.ttl won't be available to the host.

> It is not usually installed on Windows and Mac or end-user GNU/Linux systems

This is a packaging error that should be fixed.  Hosts could include them, though.

**Comment by unfa** [comment]
Fabulous!
