### ISSUE TITLE
Auto play sample preview, small issue on selecting sample, set favorites folder

### ISSUE THREAD

**Issue by Tremeschin** [iurie-sw/geonkick#131]
I just compiled GeonKick from the master branch and before everything, thanks a lot for your work put into the issue #107 regarding the user experience for better sample manipulation, the usability of GeonKick is a lot better now.

I tried this new version (will be 2.4 as far as I can tell) and I've got one problem and two requests.

- Request 1: Can we have a toggable button for auto playing a sample whenever we select it on the sample browser? It's a bit repetitive having to click "Play" whenever I want to hear the sound (the preview kinda balances this as we can have a rough idea of how the sample should sound by the waveform)

- Request 2: Can we have a favorite folder at the left? For me on the standalone binary it only shows my "Home", "Desktop" and "Downloads" and it is a bit repetitive going to the Home folder and digging down three folders to find my samples where I have them.

- Problem: Whenever I select a sample to an oscillator the area of the file tree explorer vanishes and leaves nothing, doesn't even assign the sample to the oscillator, I think it should go back to the "Controls" tab and set the double clicked audio file to the selected oscillator.

Thanks again, I'm very happy contributing ideas to such a great project, didn't create three separate issues as all the three points are kinda close together.

**Comment by iurienistor** [comment]
Hi! Thank you for testing :) Yes, the request 1 is a good idea, and I think can be added easily in the current release. I'll see if I can add request 2 into the current release (maybe in the next one) because I am close to finishing the preparation for this release.

**Comment by iurienistor** [comment]
>     * Problem: Whenever I select a sample to an oscillator the area of the file tree explorer vanishes and leaves nothing, doesn't even assign the sample to the oscillator, I think it should go back to the "Controls" tab and set the double clicked audio file to the selected oscillator.

Strange, I can't reproduce. Are you sure that you have the last changes from the master? Because if the browser "is closed" / vanishes when double click it means that you don't have last changes.

**Comment by iurienistor** [comment]
Request 1 - implemented, now is in master. Toggle button was not added because I don't think is needed. Now on single-lick it plays the sample.

**Comment by Tremeschin** [comment]
I'll test both last comments of you by tomorrow, maybe running it on plugin mode changes something, who knows.. and I think I was on Wayland so will boot Xorg for testing it also!!

**Comment by Tremeschin** [comment]
Hey! Just compiled from master and the issue of it not assigning the sample to an oscillator is gone, plus auto playing the samples makes it a lot simpler to use and quickly find a good sample!!

I'm closing the issue as you stated:

> The request 2 will be implemented in the next major release when I'll make further UI updates (there will not be any minor releases until 3.0).

And I see you created the issue #133

Thanks a lot for hearing suggestions from us, end users :)
