### ISSUE TITLE
Further UI updates

### ISSUE THREAD

**Issue by iurienistor** [iurie-sw/geonkick#133]
There will more UI updates, and polishing the design.

**Comment by trebmuh** [comment]
I'd be great to have the version number displayed on the UI.
That would help when troubleshooting people.

Quick mockup (upper-left corner):
![geonkick-prez](https://user-images.githubusercontent.com/8705846/100367954-43797300-3003-11eb-9e3c-f6f3558d6914.png)

**Comment by iurienistor** [comment]
@trebmuh, yes. Thus, Have created the issue: https://github.com/iurie-sw/geonkick/issues/144
