### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by krznv** [iurie-sw/geonkick#142]
/home/krznv/geonkick/src/GeonkickConfig.cpp:117:65: error: ‘setprecision’ is not a member of ‘std’
         jsonStream << "\"scaleFactor\": " << std::fixed << std::setprecision(2) << scaleFactor << std::endl;

Not very experienced at this, running Debian. Dependencies are installed.

**Comment by trebmuh** [comment]
Which Debian version are you running?

**Comment by quadrillionth** [comment]
kerznv,

that looks like the error i just had. running mint debian myself. i had help resolving this also. try this:

clean everything (redkite and geonkick).

then download and install these instead:

https://github.com/iurie-sw/redkite/releases/tag/v1.2.0

https://github.com/iurie-sw/geonkick/releases/tag/v2.5.0

you may get one more error when building geonkick (something about setprecision). if so add (without quotes) the following into the GeonKickConfig.cpp file in the src folder: "#include <iomanip>"

use this page as a reference if needed:
https://github.com/iurie-sw/geonkick/blob/master/src/GeonkickConfig.cpp

an aside: if you intend to run geonkick as a plug-in in ardour, you may need to copy the geonkick.lv2 folder from /usr/local/lib/lv2/ into /usr/lib/lv2/

**Comment by krznv** [comment]
@trebmuh I'm running 10 (buster)

@quadrillionth I will try your fix, will let you know how it goes

**Comment by krznv** [comment]
Building Redkite went fine, with Geonkick I get
CMake Error at CMakeLists.txt:205 (message):
  can't find jack library

Probably due to libjack-dev not being installed. The problem is it needs libjack0 which removes jackd, jackd2 and qjackctl.

**Comment by trebmuh** [comment]
> @trebmuh I'm running 10 (buster)

I've made a package for Geonick 2.5.0 on Debian Buster for LibraZiK-3. [See here](https://download.tuxfamily.org/librazik/pasapas/pool/main/g/geonkick/).
Feel free to use it.

**Comment by trebmuh** [comment]
> @trebmuh I'm running 10 (buster)

@krznv , I've made a package for Geonick 2.5.0 on Debian Buster for LibraZiK-3. [See here](https://download.tuxfamily.org/librazik/pasapas/pool/main/g/geonkick/).
Feel free to use it.

**Comment by quadrillionth** [comment]
krznv,
these dependencies worked on my system: 
**libjack-jackd2-dev** (instead of libjack-dev)
**libsndfile1-dev** (instead of libsndfile-dev)

**Comment by iurienistor** [comment]
Hi! I just released a fix for Geonkick regarding  std::fixed : https://github.com/iurie-sw/geonkick/releases/tag/v2.5.1.
