### ISSUE TITLE
crashing when opening gui in MusE

### ISSUE THREAD

**Issue by spamatica** [iurie-sw/geonkick#147]
Trying to run 2.6 of geonkick (actually git) but it crashes when I try to open the gui.

Here is a back trace, any idea what the problem might be?

Core was generated by `/home/ddskrjo/muse_debug/bin/muse4 -len -t'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f46b04accb4 in RkObject::RkObjectImpl::addObserver(std::unique_ptr<RkObserver, std::default_delete<RkObserver> >) () from /usr/local/lib/lv2/geonkick.lv2/libgeonkick_lv2.so
[Current thread is 1 (Thread 0x7f46c7ec1d00 (LWP 15654))]
(gdb) bt
#0  0x00007f46b04accb4 in RkObject::RkObjectImpl::addObserver(std::unique_ptr<RkObserver, std::default_delete<RkObserver> >) () at /usr/local/lib/lv2/geonkick.lv2/libgeonkick_lv2.so
#1  0x00007f46b04ac103 in RkObject::rk__add_observer(std::unique_ptr<RkObserver, std::default_delete<RkObserver> >)
    () at /usr/local/lib/lv2/geonkick.lv2/libgeonkick_lv2.so
#2  0x00007f46b046d076 in KitModel::KitModel(RkObject*, GeonkickApi*) ()
    at /usr/local/lib/lv2/geonkick.lv2/libgeonkick_lv2.so
#3  0x00007f46b0443647 in MainWindow::MainWindow(RkMain*, GeonkickApi*, RkNativeWindowInfo const&) ()
    at /usr/local/lib/lv2/geonkick.lv2/libgeonkick_lv2.so
#4  0x00007f46b0414123 in gkick_instantiate_ui(_LV2UI_Descriptor const*, char const*, char const*, void (*)(void*, unsigned int, unsigned int, unsigned int, void const*), void*, void**, _LV2_Feature const* const*) ()
    at /usr/local/lib/lv2/geonkick.lv2/libgeonkick_lv2.so
#5  0x00007f46d0579f3e in MusECore::LV2Synth::lv2ui_ShowNativeGui(MusECore::LV2PluginWrapper_State*, bool, MusECore::PluginQuirks::NatUISCaling) (state=0x55c5c99ac820, bShow=true, fixScaling=MusECore::PluginQuirks::GLOBAL)
    at /home/ddskrjo/dev/muse/muse3/muse/lv2host.cpp:1573
#6  0x00007f46d05886b4 in MusECore::LV2SynthIF::showNativeGui(bool) (this=0x55c5c9acdb80, bShow=true)
    at /home/ddskrjo/dev/muse/muse3/muse/lv2host.cpp:5173
#7  0x00007f46d0b2a6c3 in MusECore::SynthI::showNativeGui(bool) (this=0x55c5c9a142f0, v=true)

**Comment by spamatica** [comment]
Backtracking a bit I found that I had multiple versions of geonkick installed. After uninstalling the deb package the UI opens, so I think you can safely close this.
I have a question though, is it possible to see somewhere which version you are actually running? I can't find it in the UI and the prebuilt binary does not seem to have any command line switches.

**Comment by iurienistor** [comment]
@spamatica Here is an issue created for this in order the user to see the version. For now, yes, I removed the about dialog but forgot to provide a way to see the version.
https://github.com/iurie-sw/geonkick/issues/144

"I had multiple versions of geonkick installed" ... I'll investigate this. It means that the plugin had different micro versions in the manifest, and the host loaded two shared libraries of geonkick of different version. It in scenario anyway it shouldn't crash. Thank you for this information.
