### ISSUE TITLE
Stereo instruments

### ISSUE THREAD

**Issue by iurienistor** [iurie-sw/geonkick#149]
An option to make instruments stereo, and synthesize right and left channel separately. Easy copy between left and right channel.

**Comment by unfa** [comment]
I wonder if maybe a L/R offset tool for controls wouldn't be better? Then if the user changes the base, the L/R offset will stay the same, saving a few clicks.

**Comment by iurienistor** [comment]
@unfa Yes, I think it is a better idea to have L/R options for controls. But I want to understand what this L/R would mean for a control because in general I still don't know what I what to mean with "stereo". :) 

For example, I want to have stereo noise for an instrument. Than different values for the seed for L/R will not make it stereo, there is a need actually to apply a stereo effect on the noise. What it would mean for a filter to have a L/R tool control?... Say, different cutoff frequency for L and R filter channel or an stereo effect applied after filter? The same , say, is with and oscillator. What it would mean for the oscillator controls like (wave type, amplitude, frequency) L/R? Different values for L and R channel or just it mean that we have an stereo effect applied on the oscillator output?
