### ISSUE TITLE
font resize/color

### ISSUE THREAD

**Issue by ehanuise** [iurie-sw/geonkick#152]
Hi.
Is there any way to change the font size and/or color in Geonkick ?
The combo of grey on grey and very small font is an accessibility issue, especially on a large screen with very small pixels.
( Coming from VCVrack where everything is vector-based and resizable, I guess I'm spoiled. Can't code unfortunately so submitting a patch is way out of my league.  )

**Comment by ehanuise** [comment]
(Using Ardour)
I see in the readme 'UI can be scaled, but it will be blurred' but didn't find how to scale it. Is this a mention of a not-yet-implemented possibility, or is this implemented ?

**Comment by iurienistor** [comment]
@ehanuise Hi! Try Left Ctrl + f - scale up the UI by factor of 2 or restore the original. I hope it will work for you. Here is a documentation but it needs an update. https://github.com/iurie-sw/geonkick/blob/master/doc/Documentation.md

**Comment by iurienistor** [comment]
@ehanuise I hope this solved your issue. I'll close it. If not, please, leave a comment here. :)

**Comment by ehanuise** [comment]
Thank you.
I gave it a try, on a 2560x1440 screen the x2 display is larger than the screen and the bottom part isn't accessible and on x1 it's too small to read the text.
But it's workable overall. x1.5 would be a nice addition, but that's nothing urgent.
Thanks a lot for the quick reply!

**Comment by iurienistor** [comment]
@ehanuise Ok, I'll try to add x1.5

**Comment by iurienistor** [comment]
@ehanuise x1.5 factor support was added, see the latest release version

**Comment by ehanuise** [comment]
You rock :-)
