### ISSUE TITLE
Daw crashed when I load a kit

### ISSUE THREAD

**Issue by sergicollado** [iurie-sw/geonkick#153]
I'm using Ardour as a Daw, on kde neon SO, with geonkick v2.7.0
steps:
Kit creation:
- I create a new kit mixing a few default presets.
- I change in this kit the input midi notes to map my device midi pad
- save this new kit
Load kit
- create a geonkick instance in a track
- after that I try to load the new kit
- Immediately crash ardour

Logs in my terminal:
`The program 'ardour-6.6.0' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
`

**Comment by iurienistor** [comment]
Hi! Thank you. I'll check.

**Comment by iurienistor** [comment]
As a first investigation, indeed, Ardour is crashing when two or more pluign UI with Geonkick will be opened and then closed. I have tested with other hosts like QTractor, Zrythnm, and MusE, and I cannot experience this problem.

**Comment by iurienistor** [comment]
I think I have fixed the problem. Please, use the latest release  of Geonkick (2.7.1) and built (important) with the latest Redkite (1.3.1) library. Thank you!

**Comment by sergicollado** [comment]
I tried again, and my ardour go on crashing, I realized there is another strange behavior, but I don't know if it's an issue of ardour or if it's related with this issue, but it's possible...  when I activated groups on the geonkick outs when I have more than one instance of geonkick ... if I select one out to select group bonded out tracks .. it also select the other out track instances.
By the way, I don't find any info about the version of geonkick in the UI, I think it could be useful to be sure thah new version were upgraded right.  Thanks a lot for you effort, this plugin is awesome, and I'm enjoining doing drums and fx sounds with it. I love it.

**Comment by iurienistor** [comment]
@sergicollado Have you built Geonkick with Redkite 1.3.1?...

**Comment by iurienistor** [comment]
@sergicollado "I think it could be useful to be sure thah new version were upgraded right."... I have made another small release where you can see the version in the UI under the compression effect region. Don't forget to build with Redkite 1.3.1

**Comment by sergicollado** [comment]
Yes of course, I build Redkit again :)

**Comment by iurienistor** [comment]
@sergicollado If you could make short video of you actions that makes the host crash, it would be useful because I cannot reproduce.

**Comment by sergicollado** [comment]
Sorry, I can't respond before, I build it again, Now the version number appears on the bottom, but it co on crashing :(, I build Redkit 1.3.1
`Reading player:Geonkick took 2 microseconds, final size = 0
The program 'ardour-6.6.0' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 23245 error_code 8 request_code 42 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
[1]    78632 segmentation fault  Ardour6
`
![Screenshot_20210303_224642](https://user-images.githubusercontent.com/708079/109877199-fe548500-7c72-11eb-9081-410d5934c7bc.png)

**Comment by iurienistor** [comment]
Thank you. I hope I'll be able to reproduce. :)
