### ISSUE TITLE
Please allow redkite to be a separate package with a cmake variable

### ISSUE THREAD

**Issue by yurivict** [iurie-sw/geonkick#156]
Both Arch Linux (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=geonkick-git) and FreeBSD have separate ```redkite``` in separate packages.

Yet version ```2.7.3``` now has redkite unconditionally bundled.

Please add a cmake variable to use separate ```redjite``` package.

**Comment by iurienistor** [comment]
From the Geonkick user or packager perspective Redkite doesn't exist, it is just a part of Geonkick code. If a distro wants to package Redkite it can do so by using it from here https://github.com/iurie-sw/redkite, but Geonkick build system or Geonkick binary will not use anything from a packaged library.
