### ISSUE TITLE
cmake does not check for rapidjson

### ISSUE THREAD

**Issue by x42** [iurie-sw/geonkick#157]
`cmake ../` completes without checking for rapidjson. Later compilation fails 

```
src/GeonkickConfig.cpp:26:10: fatal error: rapidjson/document.h: No such file or directory
   26 | #include <rapidjson/document.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
```

Installing `rapidjson-dev` solves this.

Ideally the configuration should already fail if that library is not available.

**Comment by iurienistor** [comment]
@x42   Hi! Yes.
