### ISSUE TITLE
Crosscompiling fails

### ISSUE THREAD

**Issue by teldra** [iurie-sw/geonkick#159]
Hello,
awesome Synth, thx!

Since v2.7.3 I have problems[1], when I try to crosscompile on Voidlinux, because of integration of redkite. Buildsystem builds  `rkpng2c` for the target, but executes it via host. (Before v2.7.3, redkite was added as hostmakedependency and so `rkpng2c` was executed correct.)
It would be awesome if geonkicks buildsystem would respect `CMAKE_CROSSCOMPILING_EMULATOR`. [2]

[1] https://github.com/void-linux/void-packages/pull/29845/checks?check_run_id=2217117549
[2] https://github.com/void-linux/void-packages/pull/29845#issuecomment-809327039

**Comment by iurienistor** [comment]
Hi! Thank you! Probably I'll generate the PNG files to C manually and remove rkpng2c from the build.

**Comment by iurienistor** [comment]
@teldra no the fix is in the master, but I'll release in the next minor release v2.8

**Comment by ericonr** [comment]
@iurienistor just as a note,  the generated `* File name: distortion_groupbox_label.png` and `  * File name: about.png` have an image size of `0x0`, so they are just empty arrays. Maybe something was missing?

**Comment by iurienistor** [comment]
@ericonr 0x0 is because the png is missing but this means also that this resources is not used. There is a need to clean up from the build and directory "src/resources" resources that are not used.
