### ISSUE TITLE
Make some sliders logarithmic rather than linear

### ISSUE THREAD

**Issue by bepzi** [iurie-sw/geonkick#47]
I notice this most with the distortion sliders; the values near 0 are the most important, the values near 1 not so important, but it's really easy to accidentally slide past the values you want. Maybe the slider should have a value of 0.25 or even 0.1 at the halfway mark, so that you get much more fine-grained control over the "useful" values of that slider.

This might be relevant to other sliders and knobs in Geonkick, too.

**Comment by iurienistor** [comment]
Hi! Thank you for rising this issue. Knobs for frequency, cut-off and resonance are logarithmic. Knobs for  Amplitude are linear. Sliders for distortion are logarithmic. But I'll see what improvements can be done here.
