### ISSUE TITLE
Change the MIDI notes used in the kit

### ISSUE THREAD

**Issue by unfa** [iurie-sw/geonkick#53]
Is it possible to change the MIDI notes used for driving the kit?

![image](https://user-images.githubusercontent.com/491704/79213212-12b84500-7e49-11ea-8c76-b8cee714f5b5.png)

**Comment by iurienistor** [comment]
You can change it by  "left click" on the grid cell.

**Comment by iurienistor** [comment]
Also click on the channel to change the channel too, double click on the name to edit the name

**Comment by iurienistor** [comment]
Ctrl + c - copy current selected percussion
    Ctrl + v - paste the copied percussion into the current selected pecussion
    Up/Down - to navigate into the kit list
    Ctrl + Up/Down - to move up/down the position of the current selected percussion from the kit lis

**Comment by unfa** [comment]
I think you're talking about something else - I see how to assign individual channels to MIDI notes, but I wonder if it's possible to change these:

![image](https://user-images.githubusercontent.com/491704/79215482-e4883480-7e4b-11ea-8d6f-e783322e4c82.png)

Say my MIDI controller outputs a different set of MIDI notes for drum pads, and I want to set Geonkick to use exactly these notes, instead of the default ones - can  reconfigure these?

**Comment by iurienistor** [comment]
I have this issue : https://github.com/geontime/geonkick/issues/31 where I want to move up/down this region... but yes, more useful is to be change them for nay value.

**Comment by iurienistor** [comment]
Depends of: https://github.com/iurie-sw/redkite/issues/20
