### ISSUE TITLE
Improve editing of kit channel names

### ISSUE THREAD

**Issue by unfa** [iurie-sw/geonkick#56]
When I want to rename a channel I need to:

1. double click
2. backspace the name `Default`
3. Type the new name
4. Accept with `Enter`

I can select the text with `Shift` + `Left Arrow` 

But when I start typing, the selection isn't replaced, like I'd expect.

I think it'd be beneficial to user workflow if the `Default` name would get selected when double-clicking:

![Screenshot_20200414_123814](https://user-images.githubusercontent.com/491704/79216051-d25ac600-7e4c-11ea-9e68-b65cdd22c3c2.png)

Then I'd expect first keystroke to replace the selected text:

![Screenshot_20200414_123903](https://user-images.githubusercontent.com/491704/79216103-ee5e6780-7e4c-11ea-9e42-07ee283b69ec.png)

Also Ctrl+C, Ctrl+X, Ctrl+V don't work on selected text.

Only hitting Delete works as expected, removing the selected text in the channel name text field.

**Comment by iurienistor** [comment]
There is a need improve the line editor in Redkite GUI toolkit. I'll try to add features to get more the standard line edit, but i can't promise.

**Comment by iurienistor** [comment]
Depends of: https://github.com/iurie-sw/redkite/issues/20
