### ISSUE TITLE
Add visual feedback to the Play button(s)

### ISSUE THREAD

**Issue by unfa** [iurie-sw/geonkick#58]
Right now the play button doesn't show any visual indication that it has done anything. It'd be good to make it blink when pressed. Or maybe even keep "active" until the sample is played, and then get deactivated once it's finished?

![Screenshot_20200414_124415](https://user-images.githubusercontent.com/491704/79216551-a7bd3d00-7e4d-11ea-81b6-d060a9cd0719.png)

**Comment by iurienistor** [comment]
Yes, I need to develop something in Redkite GUI toolkit to enable this.
