### ISSUE TITLE
Mixer in the Kit view

### ISSUE THREAD

**Issue by unfa** [iurie-sw/geonkick#60]
It seems there's room fro a mixer interface in the Kit view - that'd be very useful to adjust levels of individual kit elements.

A crude mockup:

![image](https://user-images.githubusercontent.com/491704/79217186-b48e6080-7e4e-11ea-9b48-dc62dee992fb.png)

**Comment by iurienistor** [comment]
Yes, there was in initial idea for this. I'll bring it into 2.5

**Comment by unfa** [comment]
Whoa! Can't wait to test this!
