### ISSUE TITLE
Create factory presets

### ISSUE THREAD

**Issue by iurienistor** [iurie-sw/geonkick#63]
Based on discussion on https://github.com/iurie-sw/geonkick/issues/62

 -  create factory presets folder
 -  all presets will be compressed
 -  add functionality to build system to prepare (un-compress) and install the factory presets presets
 -  update README to ask users to share with presets

**Comment by unfa** [comment]
I'd like to make some decent EDM kit in Geonkick, I'm just waiting for the kit functionality to get a bit more streamlined.

**Comment by iurienistor** [comment]
@unfa I have added your tutorial presets under CC-BY 4.0 in the development branch. Is it ok? - https://github.com/iurie-sw/geonkick/blob/develop/presets/UnfaTutorial.tar.xz
