### ISSUE TITLE
Factory presets

### ISSUE THREAD

**Issue by iurienistor** [iurie-sw/geonkick#65]
If you are using Geonkick, have created some presets and want to be included in the factory presets in order Geonkick users to use them, please, attach here with a comment your archive of presets. The license of the presets accepted will be:

  - CC-BY-SA
  - CC-BY
  - CC0

Other licenses that are compatible with the above ones.

**Comment by trebmuh** [comment]
> Other licenses that are compatible with the above ones.

[Free Art Licence 1.3](http://artlibre.org/licence/lal/en/) is [compatible with CC BY-SA 4.0](https://creativecommons.org/2014/10/21/big-win-for-an-interoperable-commons-by-sa-and-fal-now-compatible/).

**Comment by magnetophon** [comment]
I made [some presets](https://gist.github.com/magnetophon/847fcc81664c997061479b2ceaf0096d), licensed under CC-BY-SA.

Some of them are in 2 parts, ether as doubles, where one part needs to be distorted and the other not, or as a left-right pair.
The names should make it clear what's what.

Hope you like them!

**Comment by iurienistor** [comment]
@magnetophon Hi, I like them :) I'll prepare and add them into factory presets. Thank you!

**Comment by iurienistor** [comment]
@magnetophon Added them here :) into develop branch. https://github.com/iurie-sw/geonkick/tree/develop/presets

**Comment by iurienistor** [comment]
@magnetophon very interesting idea about creating L R percussion and assigning the same key :) and different channels... sounds really cool!...

**Comment by magnetophon** [comment]
Thanks, but it's nothing special. Common trick with multitimbral synths.
:)

**Comment by iurienistor** [comment]
"Common trick with multitimbral synths." ... correct, but since I don't have practise on this, I have realized that this method has big potential to make interesting sounds. Now I am thinking if I can optimize this method into Geonkick.

**Comment by magnetophon** [comment]
It would be great if you could map a sound to a velocity range.

**Comment by iurienistor** [comment]
> It would be great if you could map a sound to a velocity range.

Yes, this is kind of my next idea... but I need to implement a library for this o use (or modify  liquidsfz ) , then I'll use it in geonkick.

**Comment by magnetophon** [comment]
Liquidsfz doesn't support velocity mapping?

**Comment by iurienistor** [comment]
> Liquidsfz doesn't support velocity mapping?

Yes, it supports, but the library is thought to load sfz files, but I need an API feature to be able to set raw buffers and set also regions/velocity parameters and some other synthesizer parameters (in RT safe manner), so, I can combine this with Geonkick.

**Comment by iurienistor** [comment]
by velocity mapping i mean... it has range velocity mapping for samples

**Comment by iurienistor** [comment]
my idea is to combine a synthesizer Geonkick + sample player = would be a sampler plyer and a sample real-time editor. Geonkick is like this now... but is is not supporting polyphony and velocity mapping (only for amplitude).
