### ISSUE TITLE
Feature request: distortion volume envelope.

### ISSUE THREAD

**Issue by magnetophon** [iurie-sw/geonkick#66]
It would often be handy to shape the volume of the distorted sound. 
As it is, there is no way to make a distorted, yet percussive sound.

**Comment by iurienistor** [comment]
Hi! I don't really understand. Distortion volume control is actually the output volume control after distortion, it control only amplitude. Only input distortion limter and drive contributes actually to the amount of distortion. There is an envelope for drive. Thus, adding an envelope for distortion volume control would mean just an amplitude envelope for total sound. Do you mean something else?

**Comment by magnetophon** [comment]
That is what I mean: just an amplitude envelope for total sound.
When you use the distortion, the general amplitude envelope effectively controls distortion amount.
There is no way to make a sound distorted from start to end, but still be loud in the beginning and quiet in the end.

I originally wanted to ask for the general amplitude to be moved after the distortion, but changed my mind while typing, because I thought it might be un-intuitive and not backwards compatible.
Maybe you find that to be the better option though, since it would mean envelope less.

**Comment by iurienistor** [comment]
Yes, I need to think how I can add here. Indeed, after applying distortion, there is a need after to shape again the amplitude. The only way is to add an envelope for total or for volume control of distortion (less confusing maybe).

**Comment by iurienistor** [comment]
I'll ad this for v2.5, or maybe before that.

**Comment by magnetophon** [comment]
Cool!
I don't think an extra envelope for total would be a good idea, since you already have one before the distortion, so yeah, confusing.
I think either ad. an envelope for the existing distortion volume param, or move the existing general amplitude after the distortion.

**Comment by iurienistor** [comment]
"envelope for the existing distortion volume param"... probably I'll go this way because I'd like in the future to add distortion effect also for oscillators... to be able to make more interesting effects.

**Comment by iurienistor** [comment]
Implemented. Adding envelope for oscillators I'll make this in the next release, because there is a need to change more the UI in order to make sense.
