### ISSUE TITLE
VST3 builds on Linux

### ISSUE THREAD

**Issue by tank-trax** [iurie-sw/geonkick#67]
Not an issue. Just a Thank you.

![Screenshot_20200427_003212](https://user-images.githubusercontent.com/41337033/80334393-11aaee80-881f-11ea-875b-b35c2e8d11d4.png)

**Comment by tank-trax** [comment]
as an aside, had to build these packages before building Geonkick

https://github.com/iurie-sw/redkite
https://github.com/rockchip-linux/rkdeveloptool
https://github.com/Tencent/rapidjson

**Comment by iurienistor** [comment]
Hi! I am glad to see it works in Bitwig too. Thank you!

**Comment by tank-trax** [comment]
Some presets are not working in Bitwig

BartBrouns and magnetophons do not produce sound even when trying Any
the TimeKit presets work but have very low audio
