### ISSUE TITLE
feature request: bezier curves

### ISSUE THREAD

**Issue by magnetophon** [iurie-sw/geonkick#72]
It would be great if Geonkick would have bezier curves.

A wonderful example is [BShapr](https://github.com/sjaehn/BShapr):
![BShapr](https://raw.githubusercontent.com/sjaehn/BShapr/master/screenshot.png)
The 4 different curve modes make it a joy to use.

**Comment by iurienistor** [comment]
There already an issue regarding this - https://gitlab.com/iurie-sw/geonkick/-/issues/129 ... but I don't know when I'll start to implement this.

**Comment by magnetophon** [comment]
Ah, yes, I was already wondering why nobody requested this before.
