### ISSUE TITLE
Assign incremental output channels to new kit elements by default

### ISSUE THREAD

**Issue by unfa** [iurie-sw/geonkick#73]
I've made a mistake on my recent livestream while using Geonkick - I forgot to change the output channel assignment on the second instrument, and I thought the fact that both play through channel 0 is a bug,

Maybe it'd be a good idea to by default increment the channel numbers, or rather: assign first free audio output to each newly added (or copied) kit element?

**Comment by iurienistor** [comment]
Hi! I'll see what can be done in this case.

**Comment by iurienistor** [comment]
The only option is to assign unused channel starting from the minimum free number, but this will make things even more confusing. I think I'll leave as it is for now. For all newly added percussion will be assigned the first channel.
