### ISSUE TITLE
Make a stereo version of LV2 plugin

### ISSUE THREAD

**Issue by unfa** [iurie-sw/geonkick#74]
I love the kit functionality, but for old users who got used to how Geonkick worked before the new way is a bit difficult to understand.

It requires manually altering routing in the DAW to get a single instrument to play through both 0 and 1 audio outputs.

Would it be possible to have a "stereo" mode for instruments, so that they occupy 2 adjacent audio outputs, instead of one?

Managing a duplicate is problematic, as the duplicates don't stay in sync.

In the stereo mode maybe a noise stereo width control would be useful?

I guess a stereo mode would also make it easier to update older patches - instead of duplicating the instrument, just enable stereo mode - this way in Ardour by default the user gets 2 channel audio output which behaves just like the old Geonkick.

**Comment by iurienistor** [comment]
Yes, I was thinking to make a stereo version of LV2 plugin, but I don't want to make different plugins like others multi/single. Probably to add just some option to make it stereo.

**Comment by alex-tee** [comment]
@iurienistor i think you can keep the ports as-is, just label them using PortGroups (http://lv2plug.in/ns/ext/port-groups#mainOutput http://lv2plug.in/ns/ext/port-groups#MonoGroup). if the ports are explicitly marked as Mono, then a host can know what to do (in Zrythm I will make it route a mono signal to both L & R). right now there is no metadata so a host just sees a bunch of audio outs and there's no guarantee to what it will do with them (in Zrythm I simply route the first 2 ports to L & R)

**Comment by iurienistor** [comment]
Ah, ok... I didn't know that LV2 has this feature. So, I need to mark the outputs as mono. Thank you!

**Comment by x42** [comment]
I don't see how port groups can solve this. They are intended for different purposes in LV2 (matching inputs to outputs, or grouping outputs). They still have a common gain stage usually.

In any case the only plugin standard that supports optional outputs is Apple's Audio Unit.

And the accepted solution for synths that are only optionally stereo is to always have two outputs and send the same signal to both (at -3dB) when they're producing a mono signal.

**Comment by x42** [comment]
I see, the plugin changed to 16 mono outputs... In that case I highly recommend to make that 32  (16 stereo pairs).

For VSTi with more than 2 outputs, the established way is to always group outputs in stereo pairs.  In your case most hosts would interpret the 16 outputs as 8 stereo pairs.

**Comment by iurienistor** [comment]
@x42 Thank you!  I have understood now ... I need to create 32 audio channels grouped by two as stereo. Thus, the DAW will know that needs to create 16 stereo channels.

**Comment by alex-tee** [comment]
that works

**Comment by unfa** [comment]
This seems like a good idea, as later we could have noise stereo width (and possibly other stereo controls) that do not require using more than one instrument within Geonkick.

**Comment by iurienistor** [comment]
It seems that I have implemented this. Grouped by stereo. In Ardour there is created 32 channels. The kit channels number say 1 corresponds to first two audio output channels. I don't know if Ardour uses the info about the group.

**Comment by x42** [comment]
I'll test it in a bit.

> I don't know if Ardour uses the info about the group

When _fanning out_ a multi-channel instrument, groups are taken into account. e.g. for the avldrums, Arodur creates 5 mono target tracks and two stereo (overhead, cymbals), named after the port-group:

https://github.com/x42/avldrums.lv2/blob/master/lv2ttl/avldrums.multi.ttl.in#L31

**Comment by iurienistor** [comment]
Ah, now I see. Thank you. :)
