### ISSUE TITLE
Make noise seed a number field, not a slider

### ISSUE THREAD

**Issue by unfa** [iurie-sw/geonkick#75]
I thought the noise seed control would be more useful as a number filed, that could be easily incremented/decremented and also copied/pasted.

The slider present right now doesn't allow for precise control.

**Comment by iurienistor** [comment]
Maybe, but there is a need to add more features for RkLineEdit box from Redkite toolkit in order to make possible copy-paste. I'll see what I can do.

**Comment by iurienistor** [comment]
This depends of : https://github.com/iurie-sw/redkite/issues/20
