### ISSUE TITLE
Number the audio outputs from #1, not from #0

### ISSUE THREAD

**Issue by unfa** [iurie-sw/geonkick#76]
For non-programmers this is very confusing.

I've realized that actually when recording a video where I use Geonkick's Kit functionality and I say I'm assigning something to the second audio output, but the value on screen is #1 (because  is the first one).

Please number them from #1, not from #0 :D

**Comment by iurienistor** [comment]
Yes, I've closed an issue regarding this, and probably forgot to commit the modifications. I'll add this into v2.5. Thank you!

**Comment by unfa** [comment]
Thanks!
