### ISSUE TITLE
Error loading certain samples in recent build

### ISSUE THREAD

**Issue by elcalenx** [iurie-sw/geonkick#77]
Hi! I built Geonkick yesterday (12 May 2020), using a fresh git clone and following the procedure in the readme. Now I noticed that whenever I try to load certain samples nothing happens, and I see the message "[ERROR] unsupported audio format" in the console output. I see that the 2.1.0 release supposedly fixed stereo samples, but seems like something is still wrong?

The samples that are giving me trouble are from Markus Hakala's 500 kicks set (there's lots of places to download them if you google). They should be 24bit stereo .wav files, as far as I can tell. But the weird thing is they seemed to work fine when I previously tried Geonkick. This was another git build made soon after the 2.0 release.

Other samples in my collection that I've tried still seem to work.

(I'm using the VST3 plugin, in Reaper, on a Debian Testing system.)

**Comment by iurienistor** [comment]
Hi! Thank you for reporting this. Markus Hakala kits ware encoded in MS WAVE with WAVEFORMATEX 24bit, that have the same file extentsion *.wav. Thus, I have added this format in the list of supported formats.

**Comment by iurienistor** [comment]
The fix commit is in the master.

**Comment by elcalenx** [comment]
Thank you! I just built the latest git version and can confirm that the samples in question work now.
