### ISSUE TITLE
Install desktop file as part of standalone build

### ISSUE THREAD

**Issue by Jacalz** [iurie-sw/geonkick#79]
Right now it seems that the .desktop file isn't being installed by make or ninja when the standalone application has been built. This means that packager like myself need to manually install it. It would be great if this could be done automatically from the cmake build system like many other programs do :)

**Comment by iurienistor** [comment]
Hi, yes there was an issue that this commit fixed 
https://github.com/iurie-sw/geonkick/commit/c366676576556e6a6f9e81edbdf5e5c0f5835008
It is in the master, and will be available in the next release soon.

**Comment by iurienistor** [comment]
@Jacalz I have just released a patch version v2.1.1 that contians also this fix. Thank you!

**Comment by Jacalz** [comment]
Thanks :) Have a great day.
