### ISSUE TITLE
UI doesn't scale / HiDPI

### ISSUE THREAD

**Issue by hfiguiere** [iurie-sw/geonkick#80]
I have an HiDPI screen (3200x1800 physical pixels on a 13"). By default the UI is unreadable.

![Screenshot from 2020-05-24 17-42-36](https://user-images.githubusercontent.com/114441/82765587-1941c100-9de6-11ea-95d1-d7533aa01535.png)

In Ardour 6, if I grow the plugin UI window size, the UI doesn't change (it does in other plugins)

![Screenshot from 2020-05-24 17-42-41](https://user-images.githubusercontent.com/114441/82765589-1e067500-9de6-11ea-9edf-290c94c1483f.png)

**Comment by iurienistor** [comment]
Yes, this in an issue that must be implemented in Redkite GUI toolkit I am developing https://github.com/iurie-sw/redkite/issues/13
I'll start to look into this after I'll release the next version of Redkite.

**Comment by iurienistor** [comment]
I have implemnted this. The user needs manually to press Left Ctrl + f to scale up. The scaling up is only by factor of 2. Another press of Left Ctrl +f will restore the original scale. This settings is saved in ~/.config/geonkick/config.json and will be loaded every time standalone or plugin will be opened. 

Scaling will make the UI to be blurred. In the future I'll improve things in Redkite and Geonkick regarding this, and even probably make this automatic HiDPI detection.
