### ISSUE TITLE
Add custom path to presets

### ISSUE THREAD

**Issue by iurienistor** [iurie-sw/geonkick#87]
Add custom path to presets
https://github.com/iurie-sw/geonkick/issues/86

**Comment by magnetophon** [comment]
>  probably I also need to take in consideration also $PATH and look there for paths that contain */share/geonkick/presets

I guess that would be one way to do it, but wouldn't it be more robust to make it variable, and have it point to $PREFIX during configuration?

Please take this with a (big) grain of salt, as I have never actually written a makefile in my life.
I basically only program in faust, nix and some shell.

**Comment by magnetophon** [comment]
I [patched](https://github.com/NixOS/nixpkgs/pull/82442/files#diff-90133b534f2a5ef116deb00379cb4073R24) around it in the package, and your current solution works for 99% of the situations, so maybe this is not such a high priority.

**Comment by iurienistor** [comment]
@magnetophon Thank you for the package! I'll think how to implement this.

**Comment by jtojnar** [comment]
On UNIX systems, you would typically use:

1. `CMAKE_INSTALL_FULL_DATADIR` variable from [GNUInstallDirs CMake module](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html)
2. At runtime, directories listed in [`$XDG_DATA_DIRS` environment variable](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables), falling back to `/usr/local/share/:/usr/share/` when not set. GLib has a [utility function](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-get-system-data-dirs) for that and so does Qt ([`GenericDataLocation`](https://doc-snapshots.qt.io/qt5-5.9/qstandardpaths.html#StandardLocation-enum)). Not sure what is the equivalent in Redkite.

**Comment by magnetophon** [comment]
> Fix loading presets from .local/geonkick/presets

Got my hopes up, but the new release doesn't yet fix this, right?

Still thanks for doing proper bug-fix releases so quickly!

**Comment by iurienistor** [comment]
@magnetophon It fixes other issue. Also I need to make an update to follow the standard https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by iurienistor** [comment]
> On UNIX systems, you would typically use:
> 
>     1. `CMAKE_INSTALL_FULL_DATADIR` variable from [GNUInstallDirs CMake module](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html)
> 
>     2. At runtime, directories listed in [`$XDG_DATA_DIRS` environment variable](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables), falling back to `/usr/local/share/:/usr/share/` when not set.

Thank you :) I'll implement this.

**Comment by iurienistor** [comment]
I have implemented the followings:
Install presets at
CMAKE_INSTALL_FULL_DATADIR/geonkick/presets. If CMAKE_INSTALL_FULL_DATADIR is not set than ${CMAKE_INSTALL_PREFIX}/share/geonkick/presets will be used

At runtime Geonkick first will look for user defined presets at $XDG_DATA_HOME/geonkick/presets. if $XDG_DATA_HOME is not set than $HOME/.local/share/geonkick/presets will be used.

The default / factory presets will be loaded from $XDG_DATA_DIRS. If $XDG_DATA_DIRS is not set than Geonkick will look into /usr/local/share/ and /usr/share/ 
The fix is in master, I'll make some more test and create a patch release.

**Comment by iurienistor** [comment]
By custom path I mean also the user to be able to a custom paths from UI. This will be implemented in the next minor releases.

**Comment by jtojnar** [comment]
> Install presets at
> CMAKE_INSTALL_FULL_DATADIR/geonkick/presets. If CMAKE_INSTALL_FULL_DATADIR is not set than ${CMAKE_INSTALL_PREFIX}/share/geonkick/presets will be used

This is unnecessary. The best practice is to include the [`GNUInstallDirs` CMake module](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html), and it will create the variable from `${CMAKE_INSTALL_PREFIX}` for you.

> At runtime Geonkick first will look for user defined presets at $XDG_DATA_HOME/geonkick/presets. if $XDG_DATA_HOME is not set than $HOME/.local/share/geonkick/presets will be used.

Sounds good.

> The default / factory presets will be loaded from $XDG_DATA_DIRS. If $XDG_DATA_DIRS is not set than Geonkick will look into /usr/local/share/ and /usr/share/
> The fix is in master, I'll make some more test and create a patch release.

Additionally, Geonkick should look into `GKICK_DATADIR / presetsPathSufix` (pass `-DGKICK_DATADIR=${CMAKE_INSTALL_FULL_DATADIR}` to compiler) since apps do not necessarily have to be installed to a location under `$XDG_DATA_DIRS` or `/usr` (`/opt` is pretty common).

**Comment by iurienistor** [comment]
@jtojnar 
Yes, now I added also GKICK_DATADIR / presetsPathSufix in the list of paths. Thank you!

**Comment by magnetophon** [comment]
It works now in 2.2.2, thank you!
