### ISSUE TITLE
Improve factory presets, add new factory presets

### ISSUE THREAD

**Issue by iurienistor** [iurie-sw/geonkick#93]
Improve factory presets, add new factory presets

**Comment by iurienistor** [comment]
@unfa
Do you think you'd like to create a KIT preset for the next release? :)

@magnetophon 
I used your presets in my track "A Dolphin Daydream". Do you think you'd like to make an update of the kit or maybe create some more presets? :)

**Comment by magnetophon** [comment]
Glad you liked them!
Where can I hear that track?

What do you mean by updating the kit? Is there anything missing or broken?
I could make another kit I guess.  Any preferences as to the direction I should go in?

**Comment by iurienistor** [comment]
@magnetophon No, nothing is broken, I thought in case if you plan updates. Yes, it would be really nice if you'll make new presets, it doesn't matter the direction . :) In the second part of the track is more evident - https://www.youtube.com/watch?v=6Stk-E7sBhc

**Comment by magnetophon** [comment]
Nice track! Which synths did you use?

**Comment by iurienistor** [comment]
@magnetophon 
Yoshimi - the majority sounds, pads, leads
General MIDI Synth from Ardour - piano from it, and other instruments
liquidsfz with VSCO orchestra library
OxeFM Synth for low end
Geonkick for percussive sounds
Effects: Ardour plugins, calf plugins and guitarix and C* caps plugins for reverb effects
DAW: Ardour
